apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: eks-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-
  directoryPerms: "777"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eks-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: eks-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-::fsap-
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: eks-efs-sc
  resources:
    requests:
      storage: 5Gi