 - name: Install Apache Tomcat10 using ansible
   hosts: localhost
   remote_user: ec2-user
   become: true
   tasks:
     - name: Create a Tomcat User
       user:
         name: tomcat
 
     - name: Create a Tomcat Group
       group:
         name: tomcat
 
     - name: Install JAVA
       yum:
         name: java-11-amazon-corretto
         state: present
 
 
     - name: Create a Tomcat Directory
       file:
         path: /opt/tomcat10
         owner: tomcat
         group: tomcat
         mode: 755
         recurse: yes
 
     - name: download & unarchive tomcat10
       unarchive:
         src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.13/bin/apache-tomcat-10.1.13.tar.gz
         dest: /opt/tomcat10
         remote_src: yes
         extra_opts: [--strip-components=1]
 
     - name: Change ownership of tomcat directory
       file:
         path: /opt/tomcat10
         owner: tomcat
         group: tomcat
         mode: "u+rwx,g+rx,o=rx"
         recurse: yes
         state: directory
 
     - name: Creating a service file
       become: yes
       copy:
        content: |-
          [Unit]
          Description=Tomcat Service
          Requires=network.target
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Environment="CATALINA_PID=/opt/tomcat10/logs/tomcat.pid"
          Environment="CATALINA_BASE=/opt/tomcat10"
          Environment="CATALINA_HOME=/opt/tomcat10"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          ExecStart=/opt/tomcat10/bin/startup.sh
          ExecStop=/opt/tomcat10/bin/shutdown.sh
          Restart=on-abnormal
          
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service
        mode: 0755
 
     - name: Start and Enable Tomcat 10 on sever
       systemd:
         name: tomcat
         state: started
         daemon_reload: true